### ISSUE TITLE
cerebellum Atlas 

### ISSUE THREAD

**Issue by eliauk07yz** [PennLINC/AtlasPack#18]
Hi 
   Can i change cerebellum Atlas in xcp_d?
for example,i want to use yeo17 cerebellum atlas?

**Comment by tsalo** [comment]
This seems a question more appropriate for the XCP-D repository. To answer your question, though, you cannot feed custom atlases into XCP-D directly, but we have written a couple of scripts to do custom processing (including parcellation with custom atlases) in the [`xcp_d-examples`](https://github.com/PennLINC/xcp_d-examples) repository. The repo might be a little out of date, but you should be able to modify the relevant code as needed without too much trouble.
