### ISSUE TITLE
Missing image data

### ISSUE THREAD

**Issue by fphsFischmeister** [PennLINC/AtlasPack#19]
Dear @tsalo,

recently came across this wonderful project and we would like to use in particular the 4S parcellations for our diffusion data. However, I am struggling with the repo and the reconstruction of the 4S templates since imaging data as well as the singularity images are missing. I managed to get all the data of the atlases, however, I cannot get beyond the first call of the the files within the transform directory.

Could you please either provide the necessary files or at least the final combined atlases?

Thanks in advance,

Florian

**Comment by tsalo** [comment]
@fphsFischmeister thanks for trying out the code! Can you share the specific errors you get when you run the scripts?

Namely,

```
bash 01_combine_subcortical.sh
```

then,

```
bash 02_supplement_schaefers.sh
```

**Comment by tsalo** [comment]
Actually, the easiest thing to do should be to clone the repo and then `datalad get` the atlases directly. @mattcieslak is that correct?

**Comment by fphsFischmeister** [comment]
dear @tsalo,

actually, I cloned the repo and used datalad and the scripts. 

- Datalad, using "datalad get -r *" states that it is impossible to get the files since the .git/annex directory is missing. Possibly you need to generate a data sibling on openneuro or some other repo.
- using the script states
```
[INFO   ] Making sure inputs are available (this may take some time) 
get(error): Schaefer/tpl-fsLR_hemi-L_den-32k_desc-nomedialwall_dparc.label.gii (file) [not available; (Note that these git remotes have annex-ignore set: origin)]
```
possibly due to the same reason, the annexed files are not available.

I was able to run the prepare_atlas.sh scripts following the deletion of the tpl_* files, however, I am stuck with the registrations, since I am lacking the simg files from the registration_scripts directory.

Thanks in advance,
Florian

**Comment by mattcieslak** [comment]
Hi Florian, did you `git clone` or `datalad clone` the repo?

**Comment by fphsFischmeister** [comment]
> Hi Florian, did you `git clone` or `datalad clone` the repo?

`datalad clone` did the trick. `git clone` is missing the osf repositories that's why I did not succeed. Tried to reflect that in the README but forking also results in a loss of the osf references.

Having cloned necessary files I will try to regenerate the atlases myself.

thanks for that wonderful package!
