### ISSUE TITLE
Replace/supplement Schaefer with Yan 2023?

### ISSUE THREAD

**Issue by tsalo** [PennLINC/AtlasPack#7]
https://github.com/ThomasYeoLab/CBIG/releases/tag/v0.28.3-Fix_parcel_order_Yan2023

**Comment by mattcieslak** [comment]
Do you think we should remove Schaefer? Or add this as an additional atlas set?

**Comment by tsalo** [comment]
Per today's scrum, we'll wait until we're sure the atlas is stable to incorporate it here.

I don't have a strong opinion about replacing our current atlases vs. adding new ones. It probably makes more sense to add new combined atlases if we're going to make an AtlasPack release with the Schaefer atlases first, so we're not pushing backwards-incompatible changes _right_ after making our first release.
