### ISSUE TITLE
CIFTI files download error when using datalad

### ISSUE THREAD

**Issue by XiaoyuXu750** [PennLINC/AtlasPack#8]
I am using datalad to download atlas files from the AtlasPack repository (https://github.com/PennLINC/AtlasPack.git).  I first installed datalad and datalad-osf, and successfully downloaded the files contained in the OSF dataset. 

However, I couldn't download all the cifti dlabel files, the error reports  [not available; (Note that these git remotes have annex-ignore set: origin)]. I tried "git annex whereis" and there is only one link "taylor@Taylors-MBP.lan:~/Documents/tsalo/AtlasPack".  I am new to datalad. Do you have any idea where is wrong?

`(dl-osf) (base) cuilab@cuilab:/mnt/e/Atlas/test$ datalad --version datalad 0.18.3`

`(dl-osf) (base) cuilab@cuilab:/mnt/e/Atlas/test$ git annex version`

`git-annex version: 10.20230215-gd24914f2a
build flags: Assistant Webapp Pairing Inotify DBus DesktopNotify TorrentParser MagicMime Benchmark Feeds Testsuite S3 WebDAV
dependency versions: aws-0.22.1 bloomfilter-2.0.1.0 cryptonite-0.29 DAV-1.3.4 feed-1.3.2.1 ghc-9.0.2 http-client-0.7.13.1 persistent-sqlite-2.13.1.0 torrent-10000.1.1 uuid-1.3.15 yesod-1.6.2.1
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2BP512E BLAKE2BP512 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL X*
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs httpalso borg hook external
operating system: linux x86_64
supported repository versions: 8 9 10
upgrade supported from repository versions: 0 1 2 3 4 5 6 7 8 9 10
(dl-osf) (base) cuilab@cuilab:/mnt/e/Atlas/test$ datalad install https://github.com/PennLINC/AtlasPack.git
[INFO   ] Detected a filesystem without fifo support.
[INFO   ] Disabling ssh connection caching.
[INFO   ] Remote origin not usable by git-annex; setting annex-ignore
[INFO   ] https://github.com/PennLINC/AtlasPack.git/config download failed: Not Found
install(ok): /mnt/e/Atlas/test/AtlasPack (dataset)`

`(dl-osf) (base) cuilab@cuilab:/mnt/e/Atlas/test/AtlasPack$ datalad get tpl-fsLR_atlas-4S152Parcels_den-91k_dseg.dlabel.nii`

`get(error): tpl-fsLR_atlas-4S152Parcels_den-91k_dseg.dlabel.nii (file) [not available; (Note that these git remotes have annex-ignore set: origin)]`

`(dl-osf) (base) cuilab@cuilab:/mnt/e/Atlas/test/AtlasPack$ git annex whereis tpl-fsLR_atlas-4S152Parcels_den-91k_dseg.dlabel.nii`
`whereis tpl-fsLR_atlas-4S152Parcels_den-91k_dseg.dlabel.nii (1 copy)
        74e0daf4-9148-464c-a765-6d5a8e68574b -- taylor@Taylors-MBP.lan:~/Documents/tsalo/AtlasPack
ok
`

**Comment by mattcieslak** [comment]
@tsalo you may need to push your local copy to osf.

**Comment by tsalo** [comment]
@mattcieslak I just did, but it looks like everything was already pushed.

**Comment by mattcieslak** [comment]
did you do `datalad push --to osf`?

**Comment by tsalo** [comment]
I did `datalad push --to osf-storage`

**Comment by tsalo** [comment]
Just did `datalad push --to origin` after the OSF storage push, so hopefully it's fixed.

**Comment by mattcieslak** [comment]
I'm able to get the data and see:

```
(2 copies)
  	74e0daf4-9148-464c-a765-6d5a8e68574b -- taylor@Taylors-MBP.lan:~/Documents/tsalo/AtlasPack
   	9dda5422-8282-46f0-95f0-4dabe79d089a -- [osf-storage]
ok
```
Please do a `git fetch` and merge main, you should see it available

**Comment by XiaoyuXu750** [comment]
Yes, I successfully downloaded ! Thank you !  😄

**Comment by tsalo** [comment]
I'm glad it works!
